app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template, redirect, url_for

from . import home

from .. import run_scraper


@home.route('/')
def homepage():
    """
    Render the homepage template on the /route
    """
    return render_template('home/index.html', title="Home")


@home.route('/about')
def about():
    """
    Render the about template on the /route
    """
    return render_template('home/about.html', title='About')


@home.route("/recarregar")
def recarregar():
    run_scraper()

    return redirect(url_for('home.homepage'))

app/templates/home/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }} | GradeGenerator</title>

    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Icons -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom style -->
    <link href="{{ url_for('static', filename='css/cover.css') }}" rel="stylesheet">

 </head>
  <body class="d-flex h-100 text-center text-white bg-dark">

<div class="d-flex  h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">GradeGenerator</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" href="{{ url_for('home.homepage') }}">Inicio</a>
        <a class="nav-link active" aria-current="page" href="{{ url_for('home.about') }}">Sobre</a>
      </nav>
    </div>
  </header>
    <main class="px-3">
    <h1>Crie a sua grade horária sem perder tempo</h1>
    <br/>
    <p class="lead">GradeGenerator foi criado para ser possível planejar o seu próximo semestre de forma rápida
    e eficiente.
        <br/><br/>
        Para isso, é possível escolher suas disciplinas, criar as suas configurações (como não ter aula com
    certo professor, ou não ter aula as 7h da manhã), e visualizar a melhor grade possível, tudo em um só lugar.
    </p>
    <h2>Como funciona</h2>
    <br/>
    <p class="lead">Cada grade horária possui uma pontuação. Essa pontuação é gerada pelos fatores selecionados na página de configuração.
      A grade exibida é a que tem a maior pontuação. <br/>
      A pontuação funciona da seguinte maneira: <br/>
      A grade tenha um professor escolhido: <b>+20 pontos/professor</b><br/>
      A grade tenha alguma aula durante um horário não desejado: <b>-7 pontos/aula</b><br/>
      A grade ultrapasse o limite máximo de aulas por dia definido: <b>-10 pontos/aula</b><br/>
      A grade nao possua o limite mínimo de aulas por dia definido: <b>-10 pontos/aula</b><br/>
      A grade possui um dia vazio (e a opção foi selecionada): <b>+15 pontos</b><br/>
      A grade possui aulas em sequência menor que o limite: <b>+5 pontos/aula</b><br/>
      A grade possui aulas em sequência ultrapssando o limite: <b>-15 pontos/aula</b><br/>
      A grade possui aulas no turno selecionado: <b>+5 pontos/aula</b><br/>
      A grade possui aulas no turno não selecionado (exceto se foi selecionado "Ambos"): <b>-5 pontos/aula</b><br/>
      A grade possui aulas sem horário definido (SHF) quando não se desejava: <b>-20 pontos/aula</b><br/>

      <br/>
      Veja o código fonte no <a href="https://github.com/Leinadium/gradeHoraria">GitHub</a>
    </p>
    </main>

  <footer class="mt-auto text-white-50">
    <p>Daniel Guimarães © 2021</p>
  </footer>
</div>
</body>
</html>

app/templates/home/index.html
<!DOCTYPE html>
<html class="h-100" lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }} | GradeGenerator</title>

    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Icons -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom style -->
    <link href="{{ url_for('static', filename='css/cover.css') }}" rel="stylesheet">

 </head>
  <body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">GradeGenerator</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="{{ url_for('home.homepage') }}">Inicio</a>
        <a class="nav-link" href="{{ url_for('home.about') }}">Sobre</a>
      </nav>
    </div>
  </header>
    <main class="px-3">
    <h1>Gerador de Grade Horária para PUC-Rio</h1>
    <p class="lead">GradeGenerator é uma ferramenta para montar sua grade automaticamente, com
    múltiplas configurações, escolhendo professores e horários, sem perder seu tempo. Exclusivo para a PUC-Rio</p>
    <p class="lead">
      <a href="{{ url_for('criar.inicio') }}" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Criar</a>
    </p>
    </main>

  <footer class="mt-auto text-white-50">
    <p>Daniel Guimarães © 2021</p>
  </footer>
</div>
</body>
</html>